export const PORTFOLIO_ITEMS = [
  {
    id: 1,
    category: "Solo Female",
    src: "solo-female-23.jpg",
    location: "Portrait Session",
  },
  {
    id: 2,
    category: "Solo Female",
    src: "solo-female-24.jpg",
    location: "Portrait Session",
  },
  {
    id: 3,
    category: "Couple",
    src: "couple-5.jpg",
    location: "Couple Session",
  },
  {
    id: 4,
    category: "Creative",
    src: "https://images.unsplash.com/photo-1493238792000-8113da705763?q=80&w=800&h=1000&auto=format&fit=crop",
    location: "Studio A",
  },
  {
    id: 5,
    category: "Pets",
    src: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?q=80&w=1000&h=1000&auto=format&fit=crop",
    location: "Highlands",
  },
  {
    id: 6,
    category: "Solo Female",
    src: "solo-female-5.jpg",
    location: "Portrait Session",
  },
  {
    id: 7,
    category: "Solo Male",
    src: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=800&h=1000&auto=format&fit=crop",
    location: "Berlin",
  },
  {
    id: 8,
    category: "Family",
    src: "family-5.jpg",
    location: "Family Session",
  },
  {
    id: 9,
    category: "Travel",
    src: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?q=80&w=800&h=1200&auto=format&fit=crop",
    location: "Chicago",
  },
  {
    id: 10,
    category: "Yoga",
    src: "https://images.unsplash.com/photo-1552196563-55cd4e45efb3?q=80&w=1000&h=1000&auto=format&fit=crop",
    location: "Rishikesh",
  },
  {
    id: 11,
    category: "Creative",
    src: "https://images.unsplash.com/photo-1547891654-e66ed7ebb968?q=80&w=1200&h=800&auto=format&fit=crop",
    location: "Museum",
  },
  {
    id: 12,
    category: "Pets",
    src: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?q=80&w=800&h=1200&auto=format&fit=crop",
    location: "Indoor",
  },
  {
    id: 13,
    category: "Family",
    src: "family-1.jpg",
    location: "Family Session",
  },
  {
    id: 14,
    category: "Family",
    src: "family-2.jpg",
    location: "Family Session",
  },
  {
    id: 15,
    category: "Family",
    src: "family-3.jpg",
    location: "Family Session",
  },
  {
    id: 16,
    category: "Family",
    src: "family-4.jpg",
    location: "Family Session",
  },
  {
    id: 17,
    category: "Family",
    src: "family-6.jpg",
    location: "Family Session",
  },
  {
    id: 18,
    category: "Family",
    src: "family-7.jpg",
    location: "Family Session",
  },
  {
    id: 19,
    category: "Family",
    src: "family-8.jpg",
    location: "Family Session",
  },
  {
    id: 20,
    category: "Family",
    src: "family-9.jpg",
    location: "Family Session",
  },
  {
    id: 21,
    category: "Family",
    src: "family-10.jpg",
    location: "Family Session",
  },
  {
    id: 22,
    category: "Family",
    src: "family-11.jpg",
    location: "Family Session",
  },
  {
    id: 23,
    category: "Family",
    src: "family-12.jpg",
    location: "Family Session",
  },
  {
    id: 24,
    category: "Family",
    src: "family-13.jpg",
    location: "Family Session",
  },
  {
    id: 25,
    category: "Family",
    src: "family-14.jpg",
    location: "Family Session",
  },
  {
    id: 26,
    category: "Family",
    src: "family-15.jpg",
    location: "Family Session",
  },
  {
    id: 27,
    category: "Family",
    src: "family-16.jpg",
    location: "Family Session",
  },
  {
    id: 28,
    category: "Family",
    src: "family-17.jpg",
    location: "Family Session",
  },
  {
    id: 29,
    category: "Family",
    src: "family-18.jpg",
    location: "Family Session",
  },
  {
    id: 30,
    category: "Family",
    src: "family-19.jpg",
    location: "Family Session",
  },
  {
    id: 31,
    category: "Family",
    src: "family-20.jpg",
    location: "Family Session",
  },
  {
    id: 32,
    category: "Family",
    src: "family-21.jpg",
    location: "Family Session",
  },
  {
    id: 33,
    category: "Family",
    src: "family-22.jpg",
    location: "Family Session",
  },
  {
    id: 34,
    category: "Family",
    src: "family-23.jpg",
    location: "Family Session",
  },
  {
    id: 35,
    category: "Family",
    src: "family-24.jpg",
    location: "Family Session",
  },
  {
    id: 36,
    category: "Family",
    src: "family-25.jpg",
    location: "Family Session",
  },
  {
    id: 37,
    category: "Family",
    src: "family-26.jpg",
    location: "Family Session",
  },
  {
    id: 38,
    category: "Family",
    src: "family-27.jpg",
    location: "Family Session",
  },
  {
    id: 39,
    category: "Family",
    src: "family-28.jpg",
    location: "Family Session",
  },
  {
    id: 40,
    category: "Family",
    src: "family-29.jpg",
    location: "Family Session",
  },
  {
    id: 41,
    category: "Family",
    src: "family-30.jpg",
    location: "Family Session",
  },
  {
    id: 42,
    category: "Couple",
    src: "couple-1.jpg",
    location: "Couple Session",
  },
  {
    id: 43,
    category: "Couple",
    src: "couple-2.jpg",
    location: "Couple Session",
  },
  {
    id: 44,
    category: "Couple",
    src: "couple-3.jpg",
    location: "Couple Session",
  },
  {
    id: 45,
    category: "Couple",
    src: "couple-4.jpg",
    location: "Couple Session",
  },
  {
    id: 46,
    category: "Couple",
    src: "couple-6.jpg",
    location: "Couple Session",
  },
  {
    id: 47,
    category: "Couple",
    src: "couple-7.jpg",
    location: "Couple Session",
  },
  {
    id: 48,
    category: "Couple",
    src: "couple-8.jpg",
    location: "Couple Session",
  },
  {
    id: 49,
    category: "Couple",
    src: "couple-9.jpg",
    location: "Couple Session",
  },
  {
    id: 50,
    category: "Couple",
    src: "couple-10.jpg",
    location: "Couple Session",
  },
  {
    id: 51,
    category: "Couple",
    src: "couple-11.jpg",
    location: "Couple Session",
  },
  {
    id: 52,
    category: "Couple",
    src: "couple-12.jpg",
    location: "Couple Session",
  },
  {
    id: 53,
    category: "Couple",
    src: "couple-13.jpg",
    location: "Couple Session",
  },
  {
    id: 54,
    category: "Couple",
    src: "couple-14.jpg",
    location: "Couple Session",
  },
  {
    id: 55,
    category: "Couple",
    src: "couple-15.jpg",
    location: "Couple Session",
  },
  {
    id: 56,
    category: "Couple",
    src: "couple-16.jpg",
    location: "Couple Session",
  },
  {
    id: 57,
    category: "Couple",
    src: "couple-17.jpg",
    location: "Couple Session",
  },
  {
    id: 58,
    category: "Couple",
    src: "couple-18.jpg",
    location: "Couple Session",
  },
  {
    id: 59,
    category: "Couple",
    src: "couple-19.jpg",
    location: "Couple Session",
  },
  {
    id: 60,
    category: "Couple",
    src: "couple-20.jpg",
    location: "Couple Session",
  },
  {
    id: 61,
    category: "Couple",
    src: "couple-21.jpg",
    location: "Couple Session",
  },
  {
    id: 62,
    category: "Couple",
    src: "couple-22.jpg",
    location: "Couple Session",
  },
  {
    id: 63,
    category: "Couple",
    src: "couple-23.jpg",
    location: "Couple Session",
  },
  {
    id: 64,
    category: "Couple",
    src: "couple-24.jpg",
    location: "Couple Session",
  },
  {
    id: 65,
    category: "Couple",
    src: "couple-25.jpg",
    location: "Couple Session",
  },
  {
    id: 66,
    category: "Couple",
    src: "couple-26.jpg",
    location: "Couple Session",
  },
  {
    id: 67,
    category: "Couple",
    src: "couple-27.jpg",
    location: "Couple Session",
  },
  {
    id: 68,
    category: "Couple",
    src: "couple-28.jpg",
    location: "Couple Session",
  },
  {
    id: 69,
    category: "Couple",
    src: "couple-29.jpg",
    location: "Couple Session",
  },
  {
    id: 70,
    category: "Couple",
    src: "couple-30.jpg",
    location: "Couple Session",
  },
  {
    id: 71,
    category: "Solo Female",
    src: "solo-female-1.jpg",
    location: "Portrait Session",
  },
  {
    id: 72,
    category: "Solo Female",
    src: "solo-female-2.jpg",
    location: "Portrait Session",
  },
  {
    id: 73,
    category: "Solo Female",
    src: "solo-female-3.jpg",
    location: "Portrait Session",
  },
  {
    id: 74,
    category: "Solo Female",
    src: "solo-female-4.jpg",
    location: "Portrait Session",
  },
  {
    id: 75,
    category: "Solo Female",
    src: "solo-female-6.jpg",
    location: "Portrait Session",
  },
  {
    id: 76,
    category: "Solo Female",
    src: "solo-female-7.jpg",
    location: "Portrait Session",
  },
  {
    id: 77,
    category: "Solo Female",
    src: "solo-female-8.jpg",
    location: "Portrait Session",
  },
  {
    id: 78,
    category: "Solo Female",
    src: "solo-female-9.jpg",
    location: "Portrait Session",
  },
  {
    id: 79,
    category: "Solo Female",
    src: "solo-female-10.jpg",
    location: "Portrait Session",
  },
  {
    id: 80,
    category: "Solo Female",
    src: "solo-female-11.jpg",
    location: "Portrait Session",
  },
  {
    id: 81,
    category: "Solo Female",
    src: "solo-female-12.jpg",
    location: "Portrait Session",
  },
  {
    id: 82,
    category: "Solo Female",
    src: "solo-female-13.jpg",
    location: "Portrait Session",
  },
  {
    id: 83,
    category: "Solo Female",
    src: "solo-female-14.jpg",
    location: "Portrait Session",
  },
  {
    id: 84,
    category: "Solo Female",
    src: "solo-female-15.jpg",
    location: "Portrait Session",
  },
  {
    id: 85,
    category: "Solo Female",
    src: "solo-female-16.jpg",
    location: "Portrait Session",
  },
  {
    id: 86,
    category: "Solo Female",
    src: "solo-female-17.jpg",
    location: "Portrait Session",
  },
  {
    id: 87,
    category: "Solo Female",
    src: "solo-female-18.jpg",
    location: "Portrait Session",
  },
  {
    id: 88,
    category: "Solo Female",
    src: "solo-female-19.jpg",
    location: "Portrait Session",
  },
  {
    id: 89,
    category: "Solo Female",
    src: "solo-female-20.jpg",
    location: "Portrait Session",
  },
  {
    id: 90,
    category: "Solo Female",
    src: "solo-female-21.jpg",
    location: "Portrait Session",
  },
  {
    id: 91,
    category: "Solo Female",
    src: "solo-female-22.jpg",
    location: "Portrait Session",
  },
]

export const CATEGORIES = ["All", "Family", "Couple", "Travel", "Yoga", "Solo Female", "Solo Male", "Pets", "Creative"]

export const TESTIMONIALS = [
  {
    id: 1,
    text: "She didn't just take photos; she captured the feeling of the wind and the silence of the moment. Absolutely timeless work.",
    author: "Elena & Marco",
    type: "Couple Shoot",
  },
  {
    id: 2,
    text: "I've never felt so comfortable in front of a lens. The urban series she shot for my brand redefined our entire aesthetic.",
    author: "Jonas K.",
    type: "Urban / Brand",
  },
  {
    id: 3,
    text: "Capturing a hyperactive husky is impossible, yet she made it look like fine art. Simply magical.",
    author: "Sarah Jenkins",
    type: "Pet Portrait",
  },
]

export const SERVICES = [
  {
    title: "Portraiture",
    price: "Starts at $60",
    desc: "Single subjects, captured in their most authentic light. Studio or on-location.",
  },
  {
    title: "The Narrative",
    price: "Starts at $80-$100",
    desc: "For couples and families. A storytelling session that documents connection and love.",
  },
  {
    title: "Commercial",
    price: "Custom Price",
    desc: "High-impact visual assets for brands, yoga studios, and urban lifestyle products.",
  },
]

export const HERO_IMAGES = [
  {
    src: "cover1.jpg",
    subtitle: "The Silence of Nature",
  },
  {
    src: "cover2.jpg",
    subtitle: "Modern Portraiture",
  },
  {
    src: "cover4.jpg",
    subtitle: "Urban Narratives",
  },
]
